name: Deploy Vitepress Site

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Build
        run: |
          npm i -g pnpm
          pnpm install
          pnpm build

          curl https://raw.githubusercontent.com/leadlang/lead/refs/heads/main/leadman_unix.sh -o ./.vitepress/dist/install.sh
          curl https://raw.githubusercontent.com/leadlang/lead/refs/heads/main/leadman_windows.ps1 -o ./.vitepress/dist/install.ps1
          curl https://raw.githubusercontent.com/leadlang/lead/refs/heads/main/leadman_unix_avd.sh -o ./.vitepress/dist/installadv.sh
          cp ./*.svg ./.vitepress/dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.vitepress/dist/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
